### PR TITLE
Allow for additional variables to be returned by data loaders of task

### PR DESCRIPTION
**Pull request by agisga**
- Allow for additional variables to be returned by data loaders of task: addressed #14 
- Additionally, this PR also adds the missing dependency `torchmetrics` to python Poetry.

### CODE REVIEW

**Comment by agisga** [comment]
I have rebased this branch on top of the latest master branch just now.

**Comment by smilesun** [comment]
did you run sh ci.sh?

**Comment by agisga** [comment]
> did you run sh ci.sh?

Yes. All tests (examples, and pytest) pass without errors. But calculating the coverage fails when I run it locally. Do you know what's the problem?

```
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]                                                                                                                          
__main__.py: error: unrecognized arguments: --cov=domainlab                                                                                                                                    
  inifile: None                                                                                                                                                                                
  rootdir: /home/gossmann/Projects/github/DomainLab  
```

**Comment by agisga** [comment]
If I remove `--cov=domainlab` from ci_pytest_cov.sh, then there are no issues.

**Pull request merged**
